-- MySQL Script generated by MySQL Workbench
-- Fri Mar 12 00:50:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eltdafpn_auto_marker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eltdafpn_auto_marker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eltdafpn_auto_marker` DEFAULT CHARACTER SET utf8 ;
USE `eltdafpn_auto_marker` ;

-- -----------------------------------------------------
-- Table `eltdafpn_auto_marker`.`assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eltdafpn_auto_marker`.`assignment` ;

CREATE TABLE IF NOT EXISTS `eltdafpn_auto_marker`.`assignment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `grade_percentage` FLOAT NOT NULL,
  `publish_assignment_date` DATETIME NOT NULL,
  `due_date` DATETIME NOT NULL,
  `due_date_notification` TINYINT NOT NULL,
  `release_grade_date` DATETIME NOT NULL,
  `release_grade` TINYINT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltdafpn_auto_marker`.`coding_standard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eltdafpn_auto_marker`.`coding_standard` ;

CREATE TABLE IF NOT EXISTS `eltdafpn_auto_marker`.`coding_standard` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltdafpn_auto_marker`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eltdafpn_auto_marker`.`course` ;

CREATE TABLE IF NOT EXISTS `eltdafpn_auto_marker`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `leader` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `release_grade` TINYINT NOT NULL,
  `year` VARCHAR(45) NULL,
  `semester` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltdafpn_auto_marker`.`course_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eltdafpn_auto_marker`.`course_users` ;

CREATE TABLE IF NOT EXISTS `eltdafpn_auto_marker`.`course_users` (
  `user_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltdafpn_auto_marker`.`output`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eltdafpn_auto_marker`.`output` ;

CREATE TABLE IF NOT EXISTS `eltdafpn_auto_marker`.`output` (
  `submission_id` INT NOT NULL,
  `test_id` INT NOT NULL,
  `status` TINYINT NOT NULL,
  `output` VARCHAR(10000) NOT NULL,
  PRIMARY KEY (`submission_id`, `test_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltdafpn_auto_marker`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eltdafpn_auto_marker`.`role` ;

CREATE TABLE IF NOT EXISTS `eltdafpn_auto_marker`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltdafpn_auto_marker`.`submission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eltdafpn_auto_marker`.`submission` ;

CREATE TABLE IF NOT EXISTS `eltdafpn_auto_marker`.`submission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `version` INT NOT NULL,
  `final` TINYINT NOT NULL,
  `marking_server_student` TINYINT NOT NULL,
  `marking_server_professor` TINYINT NOT NULL,
  `partial_grade` FLOAT NULL,
  `final_grade` FLOAT NULL,
  `submitted` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltdafpn_auto_marker`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eltdafpn_auto_marker`.`task` ;

CREATE TABLE IF NOT EXISTS `eltdafpn_auto_marker`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assignment_id` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `class_name` VARCHAR(45) NOT NULL,
  `try` INT NOT NULL,
  `grade_percentage` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltdafpn_auto_marker`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eltdafpn_auto_marker`.`test` ;

CREATE TABLE IF NOT EXISTS `eltdafpn_auto_marker`.`test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `test_type_id` INT NOT NULL,
  `coding_standard_id` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `input_test` VARCHAR(45) NOT NULL,
  `output_test` VARCHAR(45) NOT NULL,
  `grade` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltdafpn_auto_marker`.`test_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eltdafpn_auto_marker`.`test_type` ;

CREATE TABLE IF NOT EXISTS `eltdafpn_auto_marker`.`test_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eltdafpn_auto_marker`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eltdafpn_auto_marker`.`user` ;

CREATE TABLE IF NOT EXISTS `eltdafpn_auto_marker`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `validated` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
